#!/bin/sh
#PBS -o /prod/forecast/work/atmos/harmonie/tmp/am_ppalgs.log
#PBS -j oe
#PBS -N am25_ppalgs00
#PBS -A mipa05nm
#PBS -k n
#PBS -l select=1:ncpus=32:mem=29gb
#PBS -l walltime=01:00:00
#PBS -m n

# Path: ~forecast/atmos/harmonie/job/

UTC=00

logfile=$HOME/run/ppalgs/am_ppalgs${UTC}.log
rm -f $logfile

exec 1>$logfile 2>&1

set -x

$HOME/atmos/harmonie/job/scripts/ppalgs_arome2_5km.sh $UTC
