#!/bin/sh
#PBS -o /prod/forecast/work/atmos/harmonie/tmp/arome_arctic_ppalgs.log
#PBS -j oe
#PBS -N arome_arctic_ppalgs06
#PBS -A mipa05nm
#PBS -k n
#PBS -l select=1:ncpus=32:mem=29gb
#PBS -l walltime=01:00:00
#PBS -m n

# Path: ~forecast/atmos/harmonie/job/

UTC=06

logfile=$HOME/run/ppalgs_arctic/arome_arctic_ppalgs${UTC}.log
rm -f $logfile

exec 1>$logfile 2>&1

set -x

$HOME/atmos/harmonie/job/scripts/ppalgs_arctic.sh $UTC
